version: '3.8'

services:
  app:
    container_name: nestjs_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=secret
      - DATABASE_NAME=testdb
    command: npm run start:dev


  db:
    container_name: mysql_db
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql

  migrate:
    container_name: prisma_migrate
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=secret
      - DATABASE_NAME=testdb
    command: npx prisma migrate deploy
    volumes:
      - .:/usr/src/app

volumes:
  db-data:
